
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: salonsdb
      POSTGRES_USER: postgre
      POSTGRES_PASSWORD: postgre
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgre -d salonsdb"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: